### ISSUE TITLE
Limiting Option

### ISSUE THREAD

**Issue by Entiffo** [nextcloud/integration_openai#10]
Add option to limit access to OpenAI integration feature only for specific groups, so we can limit, what personnel has access to this feature.

**Comment by julien-nc** [comment]
Hi. You can restrict the app to be used by only some groups in the apps settings. Select the app, it should open the right sidebar. Then in the "Details" tab, there is a "Limit to groups" checkbox.

I just tried it and it is effective for the OpenAI integration.
