### ISSUE TITLE
/settings/admin/connected-accounts missing

### ISSUE THREAD

**Issue by JosefAschauer** [nextcloud/integration_openai#116]
### Which version of integration_openai are you using?

2.03

### Which version of Nextcloud are you using?

AIO v29.0.4 

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox / Edge / Chrome

### Describe the Bug

according to the description of the LocalAI AIO community container, there should be a settings page https://fqdn.of.my.server/settings/admin/connected-accounts to configure models. However, this does not exist in the menu and if I open that URL directly, I'm getting access forbidden as an admin

### Expected Behavior

https://fqdn.of.my.server/settings/admin/connected-accounts would open as all other admin settings are opening

### To Reproduce

install the current Nextcloud AIO version, intall the LocalAI community container, install OpenAI integration addin in nextcloud and try to open https://fqdn.of.my.server/settings/admin/connected-accounts as an admin

**Comment by kyteinsky** [comment]
Hi, the settings have been moved to the Artificial Intelligence section, i.e. `/settings/admin/ai`. Please reopen if this doesn't solve your problem.
