### ISSUE TITLE
Not working in collabora office in android

### ISSUE THREAD

**Issue by ManuXD32** [nextcloud/integration_openai#12]
I have noticed that everything works just fine using the web based collabora office, you can choose pick link and then choose open AI things, on the contrary, this does not happen when opening a document using nextcloud android app, you click on pick link but then nothing happens, no window opens to let you choose.

**Comment by julien-nc** [comment]
Thanks for the issue.
This is expected as the authentication is handled differently in a mobile context. There is no Nextcloud session.
For that and for other reasons, the Smart Picker can't be used in a mobile client.
Things could still be improved in Nextcloud Office (the richdocuments app). The "pick link" menu item could be hidden in mobile context.
Could you create an issue there?

**Comment by MB-Finski** [comment]
I'm closing this issue at the integration_openai end since the integration itself is working as expected.

-Sami
