### ISSUE TITLE
Text Generation Fails

### ISSUE THREAD

**Issue by tkawchak** [nextcloud/integration_openai#14]
Went through the setup, and image generation is working fine. However, I see the following error when trying to use the text generation

Prompt - The default suggested (also fails with other prompts too).
```
What is the matter with putting pineapple on pizza?
```

Error message
```
The server encountered an unknown error while parsing the [object command.
```

I don't see any errors in the admin logging settings.

**Comment by MB-Finski** [comment]
Just checking in: Do you still have this issue? If it's still a thing, I could try and reproduce this issue if you specify your setup in a bit more detail (specific Nexcloud version would be a good start). On 27.1.1 and 28 dev I'm, unfortunately unable to reproduce this issue.

-Sami

**Comment by tkawchak** [comment]
I haven't seen the issue in a while since upgrading. It was probably an issue with an earlier version.
