### ISSUE TITLE
Chunking for summarize

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/integration_openai#150]
Let's implement chunking in the same way it was done in LLM2 to allow summarizing texts that are longer than the model context size.

* Implement chunking (maybe have the chunking logic in a service so it can later be used by other providers like "extract topics")
* Make the chunk size configurable in the admin settings
* Test with GPT-3.5, GPT-4 and a few small models with LocalAI (or another self hosted service)

**Comment by edward-ly** [comment]
I'm looking at the OpenAI API reference and I can't find any information regarding splitting an input prompt into chunks. If the prompt is longer than `context_size - max_output_tokens`, is it possible that the API automatically chunks the input for us?

Here's the documentation for the endpoints used by the summary provider:
https://platform.openai.com/docs/api-reference/chat/create
https://platform.openai.com/docs/api-reference/completions/create

**Comment by julien-nc** [comment]
Hey, sorry for the late answer.
The goal is to do the chunking on the app side like it's done in LLM2.
The logic would be: Perform chunking only if there is a chunk size defined in the admin settings.

You don't need the max context size of the model. It's up to the admins to choose a chunk size depending on the model they use.
