### ISSUE TITLE
Feature request: Enable per user API key settings

### ISSUE THREAD

**Issue by helheimcloud** [nextcloud/integration_openai#16]
Enabling either Admins or users to set their own/assign a API key, instead of the whole organization. This could be helpful to create usage reports by user, by assigning each a different API key. 

Is this possible?

**Comment by julien-nc** [comment]
Hey, that makes sense. This is included in v1.0.8 which is out.
The admin API key is used as fallback when a user does not have any.
Could someone confirm it works as expected?

**Comment by aris-l** [comment]
It doesn't work if a user set an API key in user settings and admin leave it blank in admin settings. 
Options can't be found in the Smart Picker.

**Comment by jonidimo** [comment]
Could be awesome if you can make an integration with local LLM like Vicuna, Falcon, Starcoder LLM or any opensource alternative. Thank you.
