### ISSUE TITLE
How do you add more then one provider?

### ISSUE THREAD

**Issue by frenzybiscuit** [nextcloud/integration_openai#160]
### Describe the feature you'd like to request

I have a stable diffusion instance running along with a regular LLM instance through Llamacpp (two providers).

I am only getting the option to add a single provider when I need to add both separate providers.

### Describe the solution you'd like

Ability to add more then one provider.

### Describe alternatives you've considered

.

**Comment by kyteinsky** [comment]
Hi, a feature request is already up for this. Let's put all conversation related to this issue in that one place.
Closing this in favour of #148
