### ISSUE TITLE
Headline generated in wrong language

### ISSUE THREAD

**Issue by janepie** [nextcloud/integration_openai#161]
### Which version of integration_openai are you using?

main

### Which version of Nextcloud are you using?

Nextcloud Hub 9 (31.0.0 dev)

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox

### Describe the Bug

When given an English text, the "generate headline" provider returns a headline in another language (I think I spotted French once, Spanish another time). 
Other languages (tested with German) work as intended.
![Image](https://github.com/user-attachments/assets/299d635b-f873-44d3-99c3-0c1ba173668f)

### Expected Behavior

Returning an English headline for an English text

### To Reproduce

1. Give an English text to the "Generate headline" provider
2. Wait for the task to get executed
3. Get headline in wrong language

**Comment by kyteinsky** [comment]
hi, would you mind attaching the text?

**Comment by janepie** [comment]
> hi, would you mind attaching the text?

Of course, taken from Assistant docs :D

Nextcloud assistant is the primary graphical user interface for interacting with artificial intelligence features in Nextcloud.

It offers the graphical user interface for the unified AI Task processing API offering features like summarizing text, generating headlines, asking arbitrary questions, transcription of media files, image generation and it integrates with the context_chat app to offer in-context answers about your own data stored in Nextcloud. The assistant app also offers a chat interface to interact with the chosen language model. Nextcloud can provide customer support upon request, please talk to your account manager for the possibilities.

**Comment by kyteinsky** [comment]
> Of course, taken from Assistant docs :D

ahh, damn
