### ISSUE TITLE
30 minutes answer

### ISSUE THREAD

**Issue by piotr-sikora-v** [nextcloud/integration_openai#168]
### Which version of integration_openai are you using?

3.2.0

### Which version of Nextcloud are you using?

30.0.3

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave	1.73.97 Chromium: 131.0.6778.108 (Official Build) (arm64) 

### Describe the Bug

Always when I send request answer took 30 minutes.
It's not depended on provider, or just using OpenAI keys (I tried also openrouter.ai).

Also I have similar problem on few my nextcloud instances... 
I'am administrator of instances running as AIO and as "normal" docker-compose community version. 

example:
![Image](https://github.com/user-attachments/assets/b6c5844e-965c-4188-bd91-09801b91385e)

### Expected Behavior

instant replay

### To Reproduce

vanilla AIO with OpenAI

**Comment by sebaxakerhtc** [comment]
I have a nextcloud instance installed about 3 years ago (H&T VM) and I'm trying to connect it to LocalAI. 
It connected successfully, I can chose models, but It doesn't work. Maybe I should wait 30 minutes... LoL
Today I installed two clean docker instances of latest Nextcloud and LocalAI. So... The result is the same.
Connection is success, models are listed, but doesn't work.
Intereesting... LocalAI logs shows repeatedly api endpoint to check health
Screenshot of LocalAI logs:
![Image](https://github.com/user-attachments/assets/a8d26671-1064-411e-8582-b591b695e07b)

**Comment by piotr-sikora-v** [comment]
I found a solution
It's here: https://docs.nextcloud.com/server/latest/admin_manual/ai/overview.html#ai-overview-improve-ai-task-pickup-speed

**Comment by githubtefo** [comment]
Are there any other solutions that don't involve occ commands?
