### ISSUE TITLE
Feature Request: Custom API Gateway

### ISSUE THREAD

**Issue by aris-l** [nextcloud/integration_openai#18]
Is it possible for users to use a custom API Gateway as an alternative to official one (api.openai.com) or the one defined by admin(s)?

**Comment by rutgerputter** [comment]
This would definitely be a great idea! I would love to integrate LocalAI in to Nextcloud, which is a self-hosted Open-AI compatible alternative. See here for more information: https://github.com/go-skynet/LocalAI/

**Comment by julien-nc** [comment]
See my comment in https://github.com/nextcloud/integration_openai/issues/15#issuecomment-1540620932 :grin:

**Comment by julien-nc** [comment]
Hey @aris-l , see my comment there: https://github.com/nextcloud/integration_openai/issues/15#issuecomment-1569960091

Closing this as duplicate.
