### ISSUE TITLE
How to use OpenAI in Nextcould

### ISSUE THREAD

**Issue by hublex** [nextcloud/integration_openai#21]
Sry for my noob question. I couldn't find the following settings.

Admin settings

There is a "Connected accounts" admin settings section to set your OpenAI API key.

**Comment by julien-nc** [comment]
No reason to be sorry :grin:.
Once you've installed the app, go to your Nextcloud settings. In the left sidebar you can see 2 title entries: "Personal" and "Administration". Under "Administration", there should be a "Connected account" entry. Click it. In this page you should see an "OpenAI integration" section.
Better?

**Comment by hublex** [comment]
Hi Julien,

thx lot for the quick answer. There wasn't any in my Settings.

[image: image.png]

I do have to contact my host, they did install nextcloud, so I do rent a
pre installed nextcloud server.I will wee what they say.


Liebe Grüße
Alexander

**Comment by julien-nc** [comment]
@hublex Are you admin of your instance? Can you check if the OpenAI integration app is installed?

**Comment by hublex** [comment]
Yeah, I should be, but my host just informed me that I am not using
Nextcloud 26, instead v.23, only. I will try to upgrade. On any earlier
versions there is no Open AI, sry for the inconvinients.
