### ISSUE TITLE
Feature request: Ask questions of arbitrary data stores / notes

### ISSUE THREAD

**Issue by ohthehugemanatee** [nextcloud/integration_openai#23]
It would be amazing to be able to query document stores in my Nextcloud with natural language and OAI. Notes app is an obvious target for this, but ideally I could just point to an arbitrary top level directory and it would use embeddings to make a chat interface for it.

**Comment by MB-Finski** [comment]
Thank you for the suggestion; it's an extremely relevant use-case! Referring to the [recent Nextcloud blog post](https://nextcloud.com/blog/german-state-nextcloud-build-digitally-sovereign-ai-for-public-sector/) there's something definitely in the works but it's not planned to be contained within this integration. With this, I'll close this issue for now...
