### ISSUE TITLE
LocalAI: Timeout too short

### ISSUE THREAD

**Issue by v3DJG6GL** [nextcloud/integration_openai#36]
### Which version of integration_openai are you using?

v1.0.4

### Which version of Nextcloud are you using?

v27.0.0

### Describe the Bug

The timeout of 60s set in _[OpenAiAPIService.php](https://github.com/nextcloud/integration_openai/blob/main/lib/Service/OpenAiAPIService.php#L289C1-L289C161)_ is - under certain circumstances - too short.
`	public function request(?string $userId, string $endPoint, array $params = [], string $method = 'GET', ?string $contentType = null, int $timeout = 60): array {`
Depending on what I want to generate, it sometimes even takes some minutes because I have no dedicated GPU for LocalAI. Therefore, integration_openai closes the connection to OpenAI in advance and the user never sees the result.

For the moment I have manually changed the value from `60` to `600` to circumvent this issue.
But it would be great if it could be fixed in a future version.
Or maybe an option to set the timeout manually in the admin settings.

### Expected Behavior

Even if some prompts take time, integration_openai will not reach the timeout limit and will wait until the result is generated.

### To Reproduce

Connect _integration_openai_ to a _LocalAI_ instance which has no dedicated GPU available and try to generate texts with more than e.g. 100 words or try to generate Pictures with Stable Diffusion which will almost never work

**Comment by markuman** [comment]
> OpenAI error: cURL error 28: Operation timed out after 60001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://192.168.178.32:8080/v1/completions

+1

**Comment by MB-Finski** [comment]
Thanks for the feature request/issue! This feature was added back in 1.0.12 but the issue was never closed.
