### ISSUE TITLE
Do not display "OpenAI" to the user when another service URL has been configured (i.e. a LocalAI URL)

### ISSUE THREAD

**Issue by orandev** [nextcloud/integration_openai#37]
### Describe the feature you'd like to request

Hello,

Could you modify all the messages (including error messages) that are displayed to the user, in order to say "OpenAI" when the service URL is OpenAI URL, and say "LocalAI" when the service URL is not OpenAI URL, please? (i.e. the following test: https://github.com/nextcloud/integration_openai/blob/main/lib/Service/OpenAiAPIService.php#L291).

Otherwise the users of the app will think what they enter in the prompt is being sent to OpenAI, when it is not the case.

And could you also hide the clickable links to openai.com website please? (if service URL is not OpenAI)
For example, there is 'href="https://openai.com/dall-e-2/"'.

### Describe the solution you'd like

For example:

ChatGPT-like text generation (by OpenAI) => ChatGPT-like text generation (by LocalAI)
AI image generation (by OpenAI Dall-E 2) => AI image generation (by LocalAI)
AI speech-to-text (Whisper via OpenAI) => AI speech-to-text (Whisper via LocalAI)
[...]

### Describe alternatives you've considered

No alternative solution.

**Comment by kyteinsky** [comment]
Hello, it was fixed some time ago. You can mention a name for the custom service.
