### ISSUE TITLE
Possibility to configure the list of sizes displayed in the "Size of the generated images" advanced setting

### ISSUE THREAD

**Issue by orandev** [nextcloud/integration_openai#42]
### Describe the feature you'd like to request

Hello,
I'm using LocalAI and stablediffusion with this app.
The stablediffusion code that is inside LocalAI does not support 1024x1024 px size for image generation, the maximum is 512x512 px (according to LocalAI doc and according to my tests).
Could you offer the possibility to the admin to configure the list of image sizes that will be displayed to the user in the "Size of the generated images" advanced setting please?

### Describe the solution you'd like

App setting (configurable with occ or in the admin UI) in order to indicate the list of image sizes we want the user to be able to select in the image generation window.
For example, a setting where we would put "256x256,512x512,1024x1024" or "256x256,512x512".

### Describe alternatives you've considered

For the moment, I've worked around this by adding the following line to lib/Service/OpenAiAPIService.php

        public function createImage(?string $userId, string $prompt, int $n = 1, string $size = Application::DEFAULT_IMAGE_SIZE): array {
                if($size == '1024x1024') { $size = '512x512'; } // workaround to avoid LocalAI stablediffusion error

**Comment by kyteinsky** [comment]
Hello, this feature was merged recently. See "Admin settings -> Artificial Intelligence -> OpenAI Integration" and in the advance options (three dots) in the assistant modal while generating an image.
