### ISSUE TITLE
LocalAI no option to set url/port

### ISSUE THREAD

**Issue by manuelkamp** [nextcloud/integration_openai#51]
### Which version of integration_openai are you using?

1.0.13

### Which version of Nextcloud are you using?

27.1.3

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge 118.0.2088.76
Firefox 119.0

### Describe the Bug

As admin i cannot find a place to set path to my LocalAI instance. Neither in the AI-settings tab (I do not know how it is spelled originally, since I use german NC) nor in the connected accounts tab.

### Expected Behavior

Have a box where I can specify my LocalAI connection details.

### To Reproduce

sign in to NC as admin and go to connected accounts -> no setting for url for LocalAI (only api key for openAI).
go to other ai setting tab -> find there no setting for url for LocalAI too.

**Comment by manuelkamp** [comment]
ok, there is anoterh connected accounts tab (a little bit confusing, maybe other name would be better). that worked as expected.

**Comment by krisgesling** [comment]
Thanks for pointing that out Manuel!

It would be great to put this in the main README somewhere. Unless I somehow missed it.

**Comment by MB-Finski** [comment]
Yeah, agreed, the readme needs an update.
