### ISSUE TITLE
LocalAI not running on public domain

### ISSUE THREAD

**Issue by manuelkamp** [nextcloud/integration_openai#53]
### Which version of integration_openai are you using?

1.0.13

### Which version of Nextcloud are you using?

27.1.3

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge, Firefox latest (not relevant)

### Describe the Bug

I am using LocalAI installation on a local only server, which is only available for the Nextcloud Server. So LocalAI is not available via Internet. I configured it in NC as such (http://srv-localai.domain.local:8080). This is working, via NC users can generate images. When using ai image generation via NC, Users use the public address of the cloud (https://cloud.somedomain.at). As a result, if they click on the generated image, it does not get shown, because the link resolves to the local only address specified in NC configuration.

### Expected Behavior

Users can click on the link and see the generated image.

### To Reproduce

Setup LocalAI
configure in NC admin settings the local (not public, because there is none defined and not wanted to be defined) address for LocalAI.
Type /, select AI image generation, generate an image, click on the generated image.

**Comment by MB-Finski** [comment]
So the front end will soon-ish be dropped from this app. Currently there's already local storage for generated images if you use the text2image_helper app as the smart picker. Quite soon, though, all AI app front-ends will be unified under the assistant app so you may want to wait for that.

**Comment by manuelkamp** [comment]
I am not sure if that is a way I like to go at the moment, since I cannot get assistant to work. I am jumping from error to error and trying to fix it - and the worse part is there is no sufficient documentation on how to get it running (or i did not find it). At the momemt i am suck in a dead end, where it wants a docker on my cloud machine, which is a no go for me. I already have a own localai instance and do not want another ai docker inside my nextcloud LXC...
