### ISSUE TITLE
Flexible API Support Required

### ISSUE THREAD

**Issue by zydisney** [nextcloud/integration_openai#62]
### Describe the feature you'd like to request

Allow user to custom completion API address.
My API address is at `{LocalAI}/v1/chat/completions`
current version POST request at`{LocalAI}/v1/completions`
My api works on some versions, so i'd like to allow user to modify the completion api address.

### Describe the solution you'd like

Add input box to allow user to custom api address

### Describe alternatives you've considered

Allow to add multiple api addresses to allow different model servers for different purposes

**Comment by MB-Finski** [comment]
Implemented in https://github.com/nextcloud/integration_openai/pull/61

**Comment by MB-Finski** [comment]
Released: https://github.com/nextcloud/integration_openai/releases/tag/v1.1.2
