### ISSUE TITLE
New release of of app?

### ISSUE THREAD

**Issue by mickenordin** [nextcloud/integration_openai#63]
### Describe the feature you'd like to request

Hello, I am wondering if there will be a new release to the appstore soon, that will include the reasent addition of basic auth support?

### Describe the solution you'd like

A new release :)

### Describe alternatives you've considered

Not having a new release seems strange and counter intuitive :)

**Comment by MB-Finski** [comment]
Yes! I'm still working on some minor additions and fixes for this release; bear with me!
