### ISSUE TITLE
NC Talk Message Translation Fails - Other OpenAI App Functions Working

### ISSUE THREAD

**Issue by reidellawfirm** [nextcloud/integration_openai#67]
### Which version of integration_openai are you using?

1.1.4

### Which version of Nextcloud are you using?

Nextcloud Hub 6 (27.1.4) (AIO)

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox on Linux

### Describe the Bug

I am selecting a short message in NC Talk to translate. I then select language to translate from 'English' and language to translate to 'Espanol (Mexico)'. After attempting I get the generic error message 'Unable to translate'. I will also note that if I do not select a translate from language (English) that it returns an error of 'Could not detect language'. 

I am assuming there is some error in pulling the the text from the message and sending it to the OpenAI API? Note that our other OpenAI integration app features are working such as image generation, speech to text, and free text prompts. 

What are some steps to troubleshoot this? Thank you.

### Expected Behavior

When I select a Talk message to translate, it is translated to the selected language. 

### To Reproduce

I am selecting a short message in NC Talk to translate. I then select language to translate from 'English' and language to translate to 'Espanol (Mexico)'. After attempting I get the generic error message 'Unable to translate'. I will also note that if I do not select a translate from language (English) that it returns an error of 'Could not detect language'.

**Comment by MB-Finski** [comment]
Thanks for the bug report! I'll add a test case for the translations for preventing this type of errors from creeping in in the future!

**Comment by reidellawfirm** [comment]
Translations did work, thank you for the quick update. I was away and finally back to update and test it.
