### ISSUE TITLE
Feature Request: Add Update Release Notes

### ISSUE THREAD

**Issue by jahknem** [nextcloud/integration_openai#7]
Add Changelog Information to the Releases. It would be more user friendly :)

**Comment by XTC-Desperado** [comment]
Check Version History in Nextcloud 1.0.9
Added
Allow using a custom service URL [#15](https://github.com/nextcloud/integration_openai/issues/15) [#18](https://github.com/nextcloud/integration_openai/issues/18) @julien-nc
New admin settings to toggle each feature [#15](https://github.com/nextcloud/integration_openai/issues/15) @julien-nc
Changed
Bump max Nextcloud version to 28 @julien-nc
Immediately update prompt history in chat/image picker components @julien-nc

**Comment by julien-nc** [comment]
The changelog is visible in the Nextcloud app settings if you select the app. That's what @XTC-Desperado means, I guess.
The releases on GitHub also include the changelog: https://github.com/nextcloud-releases/integration_openai/releases/tag/v1.0.9

@jahknem Where would you expect to see the changelog?

**Comment by jahknem** [comment]
On the releases page. I know it's already under changelog.md, but when only browsing the releases it's easier to see what has been changed

**Comment by julien-nc** [comment]
> On the releases page

If you click on "All releases" in the appstore:
https://apps.nextcloud.com/apps/integration_openai/releases?platform=27#27

**Comment by jahknem** [comment]
Thank you!
