### ISSUE TITLE
Support Mistral AI

### ISSUE THREAD

**Issue by rloutrel** [nextcloud/integration_openai#76]
### Describe the feature you'd like to request

I wish I could use Mistral AI instead of Open Ai

### Describe the solution you'd like

When configuring the openAI and LocalAI account integration (as Administrator and/or as a normal user), I would like to have the choice of Mistral AI (https://docs.mistral.ai/#api-access).

From what I understood, technically, endpoints and API structure equivalent to the openAI is available for easy port of applications. Ref: https://mistral.ai/news/la-plateforme/

### Describe alternatives you've considered

Suggest a "integration_mistralai" project. But I considered, that the user experience (admin AND final user) would be better if all AI integration configurations are grouped (as long as it is 'light' to maintain).

**Comment by rloutrel** [comment]
For the discussion, it is a french solution, avoiding the use of a non-EU solution, for customers expecting a better control of their data.
DISCLAIMER: MAYBE the servers of mistral AI are located out of EU (I did not investigate further), but I think it is not the case.

**Comment by rloutrel** [comment]
Just by providing the API url (like for localAi)?

I will give a try tonight.

**Comment by traklo** [comment]
When using Mistral API you need to provide the model name as a part of your request:
https://docs.mistral.ai/#api-access-with-the-mistral-ai-platform

There's no way to add a model via settings/admin/connected-accounts and the ChatGPT-like text generation window (accessed in Text editor via smart picker) does not allow for manual input of the model to use (presumably it would not work anyway).

Anyone had luck tinkering with this?

**Comment by thiswillbeyourgithub** [comment]
May I suggest instead relying directly on [litellm](https://docs.litellm.ai/docs/providers) instead of reinventing a part of the wheel. It allows supporting hundrers of models and virtually all providers (including localai!) with a unified syntax: `mistral/mistral-large` or `openai/gpt-4-0125-preview` etc

**Comment by julien-nc** [comment]
This app can use MistralAI after a small adjustment.
Just setting `https://api.mistral.ai` as service URL and selecting the "Chat completions" endpoint (the MistralAI API does not support `/v1/completions`).
The small issue was that integration_openai always adds a 'user' parameter in the chat completion requests which is rejected by the MistralAI API. This was  fixed in 545134fef52044b713d935ded32d6ce523924f00 which will be included in the next release (v2.0.1) which is coming soon.

![image](https://github.com/nextcloud/integration_openai/assets/11291457/0f9173ab-057c-4172-87e2-2cdddca57d94)

**Comment by mitexleo** [comment]
I'm getting 401 error. Can't even load the models now.

**Comment by julien-nc** [comment]
@mitexleo We need more information. Anything in the browser logs? Any error message in the failing network request when getting the models? Any error in nextcloud.log (server logs)?

**Comment by mitexleo** [comment]
> [@mitexleo](https://github.com/mitexleo) We need more information. Anything in the browser logs? Any error message in the failing network request when getting the models? Any error in nextcloud.log (server logs)?

Thanks for responding quickly. The issue seems to be resolved after reloading the page. I've switched to Groq for now.

**Comment by mursonic** [comment]
Hello!

I also get a client error: `GET https://api.mistral.ai/chat/completions/models` resulted in a `404 Not Found` response

The /models slug is somehow automatically added. No idea how to avoid this

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/39aadddb-7462-41de-b0d1-89e56b97ef7e" />

**Comment by julien-nc** [comment]
@mursonic The service URL is the root path of the API. You should set `https://api.mistral.ai/v1`.
The models will then be obtained at `https://api.mistral.ai/v1/models`, the chat completions will be obtained at `https://api.mistral.ai/v1/chat/completions` etc...

**Comment by mursonic** [comment]
@julien-nc Thank you so much for your support! I realise that I made a mistake, but I'm still getting 404 errors.

![Image](https://github.com/user-attachments/assets/ac07c649-f5f8-411f-9afd-3a2a70b2b80c)

**Comment by julien-nc** [comment]
@mursonic You're welcome.
Mistral does not support image generation. They produce LLMs.

See https://docs.mistral.ai/#explore-the-mistral-ai-apis

**Comment by julien-nc** [comment]
@mursonic The API response tells you that one parameter in the request is forbidden: `max_completion_tokens`.
OpenAI recently changed `max_tokens` to `max_completion_tokens`. I guess all the OpenAI-compatible APIs out there (like MistralAI) still expect `max_tokens`.

There is a setting to choose which one is sent, a bit lower in the admin settings:

![Image](https://github.com/user-attachments/assets/f859735d-04d6-4ea2-83ba-726f79be7316)

Uncheck this and you're good to go.

**Comment by mursonic** [comment]
@julien-nc Thank you so much for your patience while we worked to solve this issue! It's slow but it's working now!

**Comment by julien-nc** [comment]
@mursonic Slow like a few seconds or slow like 5 minutes?

Are you running `occ background-job:worker "OC\TaskProcessing\SynchronousBackgroundJob"`? If not, see:
https://docs.nextcloud.com/server/latest/admin_manual/ai/overview.html#ai-overview-improve-ai-task-pickup-speed

**Comment by mursonic** [comment]
@julien-nc Oh, you are too kind! Yes, about five minutes – thank you so much!

**Comment by dhx** [comment]
worked flawlessly with the unchecked max_completion_tokens setting until around two weeks ago, now we're getting this error indicating a missing messages field?
...
"CustomMessage":"API request error : Client error: `POST https://api.mistral.ai/v1/completions` resulted in a `422 Unprocessable Entity` response:
{"detail":[{"type":"missing","loc":["body","messages"],"msg":"Field required","input":{"model":"mistral-large-latest","p (truncated...)

**Comment by frozenbanana** [comment]
Has anyone tried to get the image generation to work?

<img width="777" height="342" alt="Image" src="https://github.com/user-attachments/assets/8b6b382a-d0a6-4e6e-8afa-b5265d5f71cf" />

Mistral seem to support image gen now.

My logs gives me this error message:

```
A TaskProcessing core:text2image task with id 80 failed with the following message: OpenAI/LocalAI's text to image generation failed with: API request error: Client error: `POST https://api.mistral.ai/v1/images/generations` resulted in a `404 Not Found` response: { "message":"no Route matched with those values", "request_id":"2ba0512a8227e16398a4b1334b6ca51c" }
```
